/// LOCALHOST
### Get Home 
GET http://localhost:3000/ 

### Get All User
GET http://localhost:3000/users

### Get One by Id User
GET http://localhost:3000/users/697bfeed1012e306b31bbf66

### Create a new one User
POST http://localhost:3000/users/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Ernandez",
    "lastName": "Cortez",
    "email": "ernancortez.jss@gmail.com"
}

### Modifiy One User
PUT http://localhost:3000/users/697bfeed1012e306b31bbf66 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Alvaro",
    "lastName": "Cortez",
    "email": "ernancortez.jss@gmail.com"
}

### Delet One User
DELETE http://localhost:3000/users/697bfeed1012e306b31bbf66

### Get All Products
GET http://localhost:3000/products

### Get One by Id Product
GET http://localhost:3000/products/697bff451012e306b31bbf67  

### Create a new one Product
POST http://localhost:3000/products/ HTTP/1.1
Content-Type: application/json

{
    "name": "Apple MacBook Air M4 16GB",
    "maker": "Apple Inc",
    "country": "Vietnaamm",
    "description": "A good and computer for study and work",
    "price": "1000",
    "stock": "5",
    "category": "Electronics"
}

### Modifiy One Product
PUT http://localhost:3000/products/697bff451012e306b31bbf67 HTTP/1.1
Content-Type: application/json

{
    "name": "Apple MacBook Air M4 16GB",
    "maker": "Apple Inc",
    "country": "Vietnam",
    "description": "A good and computer for study and work",
    "price": "1000",
    "stock": "5",
    "category": "Electronics"
}

### Delet One Product
DELETE http://localhost:3000/products/69742bef61d38c3eceaf54bb
