/// LOCALHOST
### Get Home 
GET http://localhost:3000/ 

### Get All User
GET http://localhost:3000/users

### Get One by Id User
GET http://localhost:3000/users/6972c2034f3b8eb1300f829b  

### Create a new one User
POST http://localhost:3000/users/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Ernandez",
    "lastName": "Cortez",
    "email": "ernancortez.jss@gmail.com",
    "favoriteColor": "brown",
    "birthday": "17/03/1965"
}

### Modifiy One User
PUT http://localhost:3000/users/696992254effa511e0807fcc HTTP/1.1
Content-Type: application/json

{
    "firstName": "Alfonso Izelo",
    "lastName": "Izelo",
    "email": "josealfonsoim.lds@gmail.com",
    "favoriteColor": "red",
    "birthday": "20/05/2008"
}

### Get All Products
GET http://localhost:3000/products

### Get One by Id Product
GET http://localhost:3000/products/6972c2034f3b8eb1300f829b  

### Create a new one Product
POST http://localhost:3000/products/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Ernandez",
    "lastName": "Cortez",
    "email": "ernancortez.jss@gmail.com",
    "favoriteColor": "brown",
    "birthday": "17/03/1965"
}

### Modifiy One Product
PUT http://localhost:3000/products/696992254effa511e0807fcc HTTP/1.1
Content-Type: application/json

{
    "firstName": "Alfonso Izelo",
    "lastName": "Izelo",
    "email": "josealfonsoim.lds@gmail.com",
    "favoriteColor": "red",
    "birthday": "20/05/2008"
}

### Delet One Product
DELETE http://localhost:3000/products/696afbe69178f213663e515d
